# Extending the jenkins-dind-image for DCOS.
# Mainly for Projects that have python dependencies. 

FROM ubuntu:16.04
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64

RUN apt-get update -y           \
    && apt-get upgrade -y       \
    && apt-get install -y       \
    apt-transport-https         \
    build-essential             \
    bzip2                       \
    ca-certificates             \
    curl                        \
    git                         \
    iptables                    \  
    jq                          \
    libbz2-dev                  \
    libffi-dev                  \
    libfreetype6-dev            \
    libpng12-dev                \
    libssl-dev                  \
    libxml2-dev                 \
    libxslt1-dev                \
    libyaml-dev                 \
    lvm2                        \
    lxc                         \
    monit                       \
    openjdk-8-jdk-headless      \
    pkg-config                  \
    python-pip                  \
    python-setuptools           \
    python-software-properties  \
    python2.7-dev               \
    software-properties-common  \
    unzip                       \
    zip

RUN pip install --upgrade virtualenv uwsgi

RUN virtualenv -p python2.7 /venv; \
    . /venv/bin/activate; \
    pip install --upgrade pip

ENV DIND_COMMIT 3b5fac462d21ca164b3778647420016315289034
# docker
RUN curl -sSL https://get.docker.com | sh
# fetch DIND script
RUN curl -sSL https://raw.githubusercontent.com/docker/docker/${DIND_COMMIT}/hack/dind -o /usr/local/bin/dind \
    && chmod a+x /usr/local/bin/dind

COPY ./wrapper.sh /usr/local/bin/wrapper.sh
RUN chmod a+x /usr/local/bin/wrapper.sh

VOLUME /var/lib/docker
ENTRYPOINT []
CMD []